stage_dir:        /u01/software
patch_target_dir: /tmp/software
patch_source_dir: /etc/ansible/WIP_PatchDBs/software

oracle_user:  oracle
oracle_group: oinstall

homes_to_patch:
  - DB19
  - DB12cR2

patch_oracle_homes:
  DB19:
    oracle_home: /u01/app/oracle/product/19.0.0/dbhome_1
    opatch_version: 12.2.0.1.24
    opatch_src_file: p6880880_190000_Linux-x86-64.zip
    stop_start_dbs: true
    install_patches:
      - "p32545013_191100_Linux-x86-64.zip"
#      - patch_number: 32545013 # DB release update JAN 2021 19.13.0.0
#        patch_name: "p32545013_191100_Linux-x86-64.zip" # DB release update JAN 2021 19.13.0.0
#     - "32545013" # DB release update JAN 2021 19.13.0.0
#    install_oneoffs:
#    remove_patches:
#    - 12345678 # a patch to be removed
    datapatch: true
  DB12cR2:
    oracle_home: /u01/app/oracle/product/12.2.0/db1
    opatch_version: 12.2.0.1.24
    opatch_src_file: p6880880_122010_Linux-x86-64.zip
    stop_start_dbs: true
    install_patches:
     - "32228578"
    datapatch: true
