---
# Apply a One-Off.
# Expect the unpacked RU('s) in <stage_dir>/p<patchid>/
# the patchfile should be unzipped there.

# Database and listener should be stopped before executing this step

 - name: "execute OPatch"
   become: true
   become_user: "{{ oracle_user }}"
   become_method: sudo
   command: sh -c "{{ item.value.oracle_home }}/OPatch/opatch apply -silent -oh {{ item.value.oracle_home }} {{ stage_dir }}/p{{ patchid }}/{{ patchid }}"
   register: opatch_output
   when: patchid not in installed_patchlist.stdout

 - name: "OPatch output"
   debug:
     msg: "{{ opatch_output.stdout }}"
   when: patchid not in installed_patchlist.stdout
